# Generated by Django 5.2.6 on 2025-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='The order in which the adjustments are presented to the user. If multiple adjustments have the same order, they will be presented in alphabetical order.')),
            ],
            options={
                'ordering': ('order', 'text'),
            },
        ),
        migrations.CreateModel(
            name='ChallengeOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dublin_indicator', models.CharField(choices=[('knowledge_and_understanding', 'Knowledge and Understanding'), ('applying_knowledge_and_understanding', 'Applying Knowledge and Understanding'), ('making_judgements', 'Making Judgements'), ('communication', 'Communication'), ('lifelong_learning_skills', 'Lifelong Learning Skills')], max_length=50)),
                ('category', models.CharField(choices=[('challenge', 'Challenge'), ('opportunity', 'Opportunity')], max_length=50)),
            ],
            options={
                'verbose_name': 'challenge or opportunity',
                'verbose_name_plural': 'challenges and opportunities',
            },
        ),
        migrations.CreateModel(
            name='UseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_level', models.CharField(choices=[('no AI', 'No AI'), ('AI planning', 'AI Planning'), ('AI collaboration', 'AI Collaboration'), ('full AI', 'Full AI'), ('AI exploration', 'AI Exploration')], max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adjustments', models.ManyToManyField(to='formdata.adjustment')),
            ],
        ),
    ]
