# Generated by Django 5.2.6 on 2025-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentform',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='challengeopportunity',
            options={'ordering': ('text',), 'verbose_name': 'challenge or opportunity', 'verbose_name_plural': 'challenges and opportunities'},
        ),
        migrations.AlterModelOptions(
            name='useexample',
            options={'ordering': ('text',)},
        ),
        migrations.AddField(
            model_name='adjustment',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assessmentform',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessmentform',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challengeopportunity',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challengeopportunity',
            name='text_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='useexample',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='useexample',
            name='text_nl',
            field=models.TextField(null=True),
        ),
    ]
