# Generated by Django 5.2.6 on 2025-09-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formdata", "0002_alter_assessmentform_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownAiUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_nl", models.TextField(null=True)),
                (
                    "assessment_forms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="known_ai_uses",
                        to="formdata.assessmentform",
                    ),
                ),
            ],
            options={
                "ordering": ("text",),
            },
        ),
        migrations.CreateModel(
            name="KnownAiUseExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_nl", models.TextField(null=True)),
                (
                    "ai_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="formdata.knownaiuse",
                    ),
                ),
            ],
            options={
                "ordering": ("text",),
            },
        ),
    ]
