# Generated by Django 5.2.6 on 2025-10-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formdata", "0003_knownaiuse_knownaiuseexample"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knownaiuse",
            options={"ordering": ("text",), "verbose_name": "Known AI use"},
        ),
        migrations.AlterModelOptions(
            name="knownaiuseexample",
            options={"ordering": ("text",), "verbose_name": "Known AI use example"},
        ),
    ]
