# Generated by Django 5.2.7 on 2025-11-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formdata", "0004_alter_knownaiuse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knownaiuseexample",
            name="assessment_form",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="known_ai_use_examples",
                to="formdata.assessmentform",
            ),
            preserve_default=False,
        ),
    ]
