# Generated by Django 5.2.8 on 2025-11-17 11:32

from django.db import migrations, models


def migrate_scale_levels(apps, schema_editor):
    """Migrate old scale level values to new ones."""
    UseExample = apps.get_model("formdata", "UseExample")

    # Mapping of old values to new values
    mapping = {
        "AI collaboration": "AI edit",
        "AI exploration": "AI specific",
    }

    for old_value, new_value in mapping.items():
        UseExample.objects.filter(scale_level=old_value).update(scale_level=new_value)


def reverse_migrate_scale_levels(apps, schema_editor):
    """Reverse migration - map new values back to old ones."""
    UseExample = apps.get_model("formdata", "UseExample")

    # Reverse mapping
    mapping = {
        "AI edit": "AI collaboration",
        "AI specific": "AI exploration",
    }

    for new_value, old_value in mapping.items():
        UseExample.objects.filter(scale_level=new_value).update(scale_level=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ("formdata", "0005_knownaiuseexample_assessment_form"),
    ]

    operations = [
        # Temporarily remove the choices constraint for the data migration.
        migrations.AlterField(
            model_name="useexample",
            name="scale_level",
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(migrate_scale_levels, reverse_migrate_scale_levels),
        migrations.AlterField(
            model_name="useexample",
            name="scale_level",
            field=models.CharField(
                choices=[
                    ("no AI", "No AI"),
                    ("AI planning", "AI Planning"),
                    ("AI edit", "AI Edit"),
                    ("AI specific", "AI Specific"),
                    ("full AI", "Full AI"),
                ],
                max_length=50,
            ),
        ),
    ]
