# Generated by Django 5.2.8 on 2025-11-20 09:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_assessment_form_to_m2m(apps, schema_editor):
    """Migrate data from ForeignKey assessment_form to M2M assessment_forms."""
    KnownAiUseExample = apps.get_model("formdata", "KnownAiUseExample")

    for example in KnownAiUseExample.objects.all():
        if example.assessment_form_id:
            example.assessment_forms.add(example.assessment_form_id)


def migrate_m2m_to_assessment_form(apps, schema_editor):
    """Reverse migration: migrate first M2M relationship back to ForeignKey."""
    KnownAiUseExample = apps.get_model("formdata", "KnownAiUseExample")
    AssessmentForm = apps.get_model("formdata", "AssessmentForm")

    # Take the first assessment form as default if the example has none.
    default_form = AssessmentForm.objects.first()
    if not default_form:
        # If no assessment forms exist, we can't reverse this migration
        raise Exception(
            "Cannot reverse migration: No AssessmentForm exists. "
            "Create at least one AssessmentForm before reversing this migration."
        )

    for example in KnownAiUseExample.objects.all():
        first_assessment_form = example.assessment_forms.first()
        if first_assessment_form:
            example.assessment_form = first_assessment_form
            example.save()
        else:
            example.assessment_form = default_form
            example.save()


class Migration(migrations.Migration):

    dependencies = [
        ("formdata", "0006_alter_useexample_scale_level"),
    ]

    atomic = False

    operations = [
        migrations.AddField(
            model_name="knownaiuseexample",
            name="assessment_forms",
            field=models.ManyToManyField(
                blank=True,
                related_name="known_ai_use_examples",
                to="formdata.assessmentform",
            ),
        ),
        # Make field nullable before migrating data
        migrations.AlterField(
            model_name="knownaiuseexample",
            name="assessment_form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="known_ai_use_examples",
                to="formdata.assessmentform",
            ),
        ),
        migrations.RunPython(
            migrate_assessment_form_to_m2m,
            reverse_code=migrate_m2m_to_assessment_form,
        ),
        migrations.RemoveField(
            model_name="knownaiuseexample",
            name="assessment_form",
        ),
    ]
