# Generated by Django 5.2.8 on 2025-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0007_remove_knownaiuseexample_assessment_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useexample',
            name='scale_level',
            field=models.CharField(choices=[('no AI', 'No AI'), ('AI planning', 'AI planning'), ('AI edit', 'AI editing and feedback'), ('AI specific', 'AI for specific tasks'), ('full AI', 'Full AI')], max_length=50),
        ),
    ]
